"use client"

import { useState, useEffect } from "react"
import { FaEdit, FaTrash, FaPlus, FaSearch, FaTimes, FaCheck } from "react-icons/fa"
import {
  PageWrapper,
  Container,
  SectionTitle,
  Input,
  Select,
  Button,
  Table,
  Th,
  Td,
  Tr,
  Label,
  FormRow,
  TextArea,
  FormContent,
  ControlsContainer,
  SearchContainer,
  InputWrapper,
  ButtonContainer,
  TableWrapper,
  CheckboxWrapper,
  Checkbox
} from "../GlobalStyles"
import apiRequest from "../../Auth/apiRequest"
import { toast } from "react-toastify"

const VendorManagement = () => {
  const [vendors, setVendors] = useState([])
  const [states, setStates] = useState([])
  const [cities, setCities] = useState([])
  const [loadingStates, setLoadingStates] = useState(false)
  const [loadingCities, setLoadingCities] = useState(false)

  const [formData, setFormData] = useState({
    vendor_type: "",
    name: "",
    address_line_1: "",
    address_line_2: "",
    city: "",
    state: "",
    pincode: "",
    contact_person: "",
    phone: "",
    email: "",
    url: "",
    kgst_tin_number: "",
    gstin: "",
    payment: "",
    terms: "",
    credit_period: "",
    export_data_code: "",
    tds_percent: "",
    igst_supplier: false,
    blacklisted_supplier: false,
    account_on_hold: false,
    reason_for_holding: "",
  })

  const [search, setSearch] = useState("")
  const [isEditing, setIsEditing] = useState(false)
  const [editingId, setEditingId] = useState(null)
  const baseUrl = process.env.REACT_APP_BACKEND_HMS_BASE_URL

  useEffect(() => {
    fetchVendors()
    fetchStates()
  }, [])

  const fetchVendors = async () => {
    try {
      const response = await apiRequest(`${baseUrl}vendor/`, "GET")
      if (response.success) {
        setVendors(Array.isArray(response.data) ? response.data : [])
      }
    } catch (error) {
      console.error("Error fetching vendors:", error)
    }
  }

  const fetchStates = async () => {
    setLoadingStates(true)
    try {
      const res = await fetch("https://countriesnow.space/api/v0.1/countries/states", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ country: "India" }),
      })
      const data = await res.json()
      if (data.data) {
        setStates(data.data.states)
      }
    } catch (error) {
      console.error("Failed to load states", error)
    } finally {
      setLoadingStates(false)
    }
  }

  const handleStateChange = async (e) => {
    const stateName = e.target.value
    setFormData((prev) => ({ ...prev, state: stateName, city: "" }))
    setCities([])

    if (!stateName) return

    setLoadingCities(true)
    try {
      const res = await fetch("https://countriesnow.space/api/v0.1/countries/state/cities", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          country: "India",
          state: stateName,
        }),
      })
      const data = await res.json()
      setCities(data.data || [])
    } catch (error) {
      console.error("Failed to load cities", error)
    } finally {
      setLoadingCities(false)
    }
  }

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }))
  }

  const handleSave = async () => {
    try {
      if (!formData.name || !formData.vendor_type) {
        toast.error("Please fill in required fields: Name and Type")
        return
      }

      let response
      if (isEditing && editingId) {
        response = await apiRequest(`${baseUrl}vendor/${editingId}/`, "PATCH", formData)
      } else {
        // vendor_id is auto-generated by backend
        response = await apiRequest(`${baseUrl}vendor/`, "POST", formData)
      }

      if (response.success) {
        toast.success(isEditing ? "Vendor updated successfully!" : "Vendor added successfully!")
        resetForm()
        fetchVendors()
      } else {
        // Enhanced error handling for field-specific errors
        if (typeof response.data === 'object') {
          const errMsgs = Object.entries(response.data)
            .map(([field, msgs]) => `${field}: ${Array.isArray(msgs) ? msgs.join(', ') : msgs}`)
            .join('\n');
          toast.error(errMsgs || response.error || "Failed to save vendor");
        } else {
          toast.error(response.error || "Failed to save vendor")
        }
      }
    } catch (error) {
      console.error("Error saving vendor:", error)
      toast.error("An unexpected error occurred")
    }
  }

  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to delete this vendor?")) return
    try {
      const response = await apiRequest(`${baseUrl}vendor/${id}/`, "DELETE")
      if (response.success) {
        toast.success("Vendor deleted successfully")
        fetchVendors()
      } else {
        toast.error(response.error || "Failed to delete vendor")
      }
    } catch (error) {
      console.error("Error deleting vendor:", error)
    }
  }

  const handleEdit = (vendor) => {
    setFormData({
      ...vendor,
      // Map backend fields to frontend if any mismatch remains
      // (but we've standardized them now)
    })
    setIsEditing(true)
    setEditingId(vendor.vendor_id || vendor.id || vendor._id?.$oid)
    if (vendor.state) {
      const event = { target: { value: vendor.state } };
      handleStateChange(event).then(() => {
        setFormData(prev => ({ ...prev, city: vendor.city }));
      });
    }
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  const resetForm = () => {
    setFormData({
      vendor_type: "",
      name: "",
      address_line_1: "",
      address_line_2: "",
      city: "",
      state: "",
      pincode: "",
      contact_person: "",
      phone: "",
      email: "",
      url: "",
      kgst_tin_number: "",
      gstin: "",
      payment: "",
      terms: "",
      credit_period: "",
      export_data_code: "",
      tds_percent: "",
      igst_supplier: false,
      blacklisted_supplier: false,
      account_on_hold: false,
      reason_for_holding: "",
    })
    setIsEditing(false)
    setEditingId(null)
    setCities([])
  }

  const filteredVendors = vendors.filter(
    (vendor) =>
      vendor.name?.toLowerCase().includes(search.toLowerCase()) ||
      vendor.email?.toLowerCase().includes(search.toLowerCase()) ||
      vendor.gstin?.includes(search) ||
      vendor.vendor_id?.includes(search),
  )

  return (
    <PageWrapper>
      <Container>
        <SectionTitle><h3>Vendor Management</h3></SectionTitle>

        <FormContent>
          <FormRow>
            <InputWrapper>
              <Label required>Supplier / Manufacturer</Label>
              <Select
                name="vendor_type"
                value={formData.vendor_type}
                onChange={handleInputChange}
              >
                <option value="">Select Type</option>
                <option value="SUPPLIER">Supplier</option>
                <option value="MANUFACTURER">Manufacturer</option>
                <option value="BOTH">Both</option>
              </Select>
            </InputWrapper>
            <InputWrapper>
              <Label required>Name</Label>
              <Input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleInputChange}
                placeholder="Enter vendor name"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>Address Line 1</Label>
              <Input
                type="text"
                name="address_line_1"
                value={formData.address_line_1}
                onChange={handleInputChange}
                placeholder="Enter address line 1"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>Address Line 2</Label>
              <Input
                type="text"
                name="address_line_2"
                value={formData.address_line_2}
                onChange={handleInputChange}
                placeholder="Enter address line 2"
              />
            </InputWrapper>
          </FormRow>

          <FormRow>
            <InputWrapper>
              <Label>State</Label>
              <Select
                name="state"
                value={formData.state}
                onChange={handleStateChange}
                disabled={loadingStates}
              >
                <option value="">{loadingStates ? "Loading states..." : "Select State"}</option>
                {states.map((s) => (
                  <option key={s.name} value={s.name}>{s.name}</option>
                ))}
              </Select>
            </InputWrapper>
            <InputWrapper>
              <Label>City</Label>
              <Select
                name="city"
                value={formData.city}
                onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                disabled={!formData.state || loadingCities}
              >
                <option value="">{loadingCities ? "Loading cities..." : "Select City"}</option>
                {cities.map((c, i) => (
                  <option key={i} value={c}>{c}</option>
                ))}
              </Select>
            </InputWrapper>
            <InputWrapper>
              <Label>Pincode</Label>
              <Input
                type="text"
                name="pincode"
                value={formData.pincode}
                onChange={handleInputChange}
                placeholder="Enter pincode"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>Contact Person</Label>
              <Input
                type="text"
                name="contact_person"
                value={formData.contact_person}
                onChange={handleInputChange}
                placeholder="Enter contact person"
              />
            </InputWrapper>
          </FormRow>

          <FormRow>
            <InputWrapper>
              <Label>Phone</Label>
              <Input
                type="tel"
                name="phone"
                value={formData.phone}
                onChange={handleInputChange}
                placeholder="Enter phone number"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>Email</Label>
              <Input
                type="email"
                name="email"
                value={formData.email}
                onChange={handleInputChange}
                placeholder="Enter email address"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>URL</Label>
              <Input
                type="url"
                name="url"
                value={formData.url}
                onChange={handleInputChange}
                placeholder="Enter website URL"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>GSTIN</Label>
              <Input
                type="text"
                name="gstin"
                value={formData.gstin}
                onChange={handleInputChange}
                placeholder="Enter GSTIN"
              />
            </InputWrapper>
          </FormRow>

          <FormRow>
            <InputWrapper>
              <Label>KGST / TIN Number</Label>
              <Input
                type="text"
                name="kgst_tin_number"
                value={formData.kgst_tin_number}
                onChange={handleInputChange}
                placeholder="Enter KGST/TIN number"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>Payment</Label>
              <Select
                name="payment"
                value={formData.payment}
                onChange={handleInputChange}
              >
                <option value="">Select Payment Mode</option>
                <option value="CASH">CASH</option>
                <option value="CHEQUE">CHEQUE</option>
                <option value="UPI">UPI</option>
                <option value="NEFT">NEFT</option>
                <option value="RTGS">RTGS</option>
              </Select>
            </InputWrapper>
            <InputWrapper>
              <Label>Credit Period (days)</Label>
              <Input
                type="number"
                name="credit_period"
                value={formData.credit_period}
                onChange={handleInputChange}
                placeholder="Enter credit period"
              />
            </InputWrapper>
            <InputWrapper>
              <Label>TDS %</Label>
              <Input
                type="number"
                step="0.01"
                name="tds_percent"
                value={formData.tds_percent}
                onChange={handleInputChange}
                placeholder="Enter TDS percentage"
              />
            </InputWrapper>
          </FormRow>

          <FormRow columns="2fr 1fr">
            <InputWrapper>
              <Label>Terms</Label>
              <TextArea
                name="terms"
                value={formData.terms}
                onChange={handleInputChange}
                placeholder="Enter payment terms"
                rows="3"
              />
            </InputWrapper>
            <InputWrapper style={{ gap: '10px', paddingTop: '28px' }}>
              <CheckboxWrapper>
                <Checkbox
                  type="checkbox"
                  name="igst_supplier"
                  checked={formData.igst_supplier}
                  onChange={handleInputChange}
                  id="igst_supplier"
                />
                <Label htmlFor="igst_supplier" style={{ marginBottom: 0 }}>IGST Supplier</Label>
              </CheckboxWrapper>
              <CheckboxWrapper>
                <Checkbox
                  type="checkbox"
                  name="blacklisted_supplier"
                  checked={formData.blacklisted_supplier}
                  onChange={handleInputChange}
                  id="blacklisted_supplier"
                />
                <Label htmlFor="blacklisted_supplier" style={{ marginBottom: 0 }}>Blacklisted Supplier</Label>
              </CheckboxWrapper>
              <CheckboxWrapper>
                <Checkbox
                  type="checkbox"
                  name="account_on_hold"
                  checked={formData.account_on_hold}
                  onChange={handleInputChange}
                  id="account_on_hold"
                />
                <Label htmlFor="account_on_hold" style={{ marginBottom: 0 }}>Account On Hold</Label>
              </CheckboxWrapper>
            </InputWrapper>
          </FormRow>

          {formData.account_on_hold && (
            <FormRow>
              <InputWrapper>
                <Label>Reason For Holding</Label>
                <TextArea
                  name="reason_for_holding"
                  value={formData.reason_for_holding}
                  onChange={handleInputChange}
                  placeholder="Enter reason for holding account"
                  rows="2"
                />
              </InputWrapper>
            </FormRow>
          )}

          <ButtonContainer>
            <Button secondary onClick={resetForm}>
              <FaTimes /> Cancel
            </Button>
            <Button onClick={handleSave}>
              {isEditing ? <FaCheck /> : <FaPlus />}
              {isEditing ? "Update Vendor" : "Save Vendor"}
            </Button>
          </ButtonContainer>
        </FormContent>

        <SectionTitle><h3>Vendor List</h3></SectionTitle>

        <ControlsContainer>
          <SearchContainer>
            <Input
              type="text"
              placeholder="Search by ID, Name, Email, or GSTIN"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <Button title="Search"><FaSearch /></Button>
          </SearchContainer>
        </ControlsContainer>

        <TableWrapper>
          <Table>
            <thead>
              <tr>
                <Th>ID</Th>
                <Th>Name</Th>
                <Th>Type</Th>
                <Th>City / State</Th>
                <Th>GSTIN</Th>
                <Th>Phone</Th>
                <Th>Action</Th>
              </tr>
            </thead>
            <tbody>
              {filteredVendors.length === 0 ? (
                <Tr>
                  <Td colSpan="7" style={{ textAlign: "center", color: "#999" }}>
                    No vendors found
                  </Td>
                </Tr>
              ) : (
                filteredVendors.map((vendor) => (
                  <Tr key={vendor.vendor_id || vendor.id || vendor._id?.$oid}>
                    <Td>{vendor.vendor_id || '-'}</Td>
                    <Td>{vendor.name}</Td>
                    <Td>{vendor.vendor_type}</Td>
                    <Td>{vendor.city || '-'}, {vendor.state || '-'}</Td>
                    <Td>{vendor.gstin || '-'}</Td>
                    <Td>{vendor.phone || '-'}</Td>
                    <Td>
                      <div style={{ display: 'flex', gap: '8px' }}>
                        <FaEdit
                          style={{ cursor: 'pointer', color: '#0d9488' }}
                          onClick={() => handleEdit(vendor)}
                          title="Edit"
                        />
                        <FaTrash
                          style={{ cursor: 'pointer', color: '#ef4444' }}
                          onClick={() => handleDelete(vendor.vendor_id || vendor.id || vendor._id?.$oid)}
                          title="Delete"
                        />
                      </div>
                    </Td>
                  </Tr>
                ))
              )}
            </tbody>
          </Table>
        </TableWrapper>
      </Container>
    </PageWrapper>
  )
}

export default VendorManagement
